### ISSUE TITLE
[Enhancement] Consider outputting to a window instead of or in addition to a file / console

### ISSUE THREAD

**Issue by PySimpleGUI** [israel-dryer/Code-Counter#4]
It seems like the output.txt file is used as a display mechanism more so than something that's utilized after the program exits.

If so, then the file output can be replaced with Prints to the debug window.  This modification worked well.

```python
    # Output stats to a window
    sg.Print('{}statistics'.format(' ' * 7))
    sg.Print('\n{}'.format('*' * 25))
    sg.Print('Count of lines: {}'.format(line_count))
    sg.Print('Count of characters: {}'.format(sum(char_count)))
    sg.Print('Avg characters per line: {}\n'.format(sum(char_count) // line_count))
    sg.Print('{}clean data'.format(' ' * 7))
    sg.Print('\n{}'.format('*' * 25))

    # write clean data to file
    for row in clean_data:
        sg.Print(row)
```

There are other ways to output to a scrolling window, but this technique was the quickest and simplest I could think of.

Also used a popup to display the summary stats.

```python
    sg.popup(f'Lines of code: {line_count}',
             f'Characters: {sum(char_count)}',
             f'Avg characters per line: {sum(char_count)//line_count}', title='Program Stats', font='Courier 15')
```

The result was these windows, perhaps not what you're after, but I like them and am using them in my version of this awesome program. 😊
![image](https://user-images.githubusercontent.com/46163555/67952021-fbe7a400-fbc2-11e9-9e26-743c8b69e323.png)

**Comment by israel-dryer** [comment]
I like this idea. I worked on compressing the code quite a big today and adding some more statistics. But, I plan on implementing something like this in the next go-round.
